apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: project1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
        - name: mycat
          image: praveenakumara/mycat:v1 
  
