apiVersion: v1
kind: Service
metadata:
  name: project1
spec:
  selector:
      app: project1
  ports:
    - port: 8090
      nodePort: 30001
      targetPort: project-port
      protocol: "TCP"
  type: NodePort

