apiVersion: v1
kind: Pod
metadata:
  name: project1
  labels:
    app: project1
spec:
  containers:
    - name: project1
      image: praveenakumara/mycat:v1
      ports:
        - name: project-port
          containerPort: 8080
