apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
spec:
  containers:
  - name: tomcat
    image: praveenakumara/mycat:v1
    volumeMounts:
    - mountPath: /data/tomcat/secret
      name: sample-secret
      readOnly: true
  volumes:
  - name: sample-secret
    secret:
      secretName: sample-secret
