apiVersion: v1
kind: Pod
metadata:
  name: secrete-pod1
spec:
  containers:
  - name: tomcat1
    image: praveenakumara/mycat:v2
    env:
      - name: myname
        valueFrom:
          secretKeyRef:
            name: sample-secret
            key: myname

      - name: mypassword
        valueFrom:
          secretKeyRef:
            name: sample-secret
            key: password
