apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: project1
spec:
  containers:
    - name: tomcat
      image: praveenakumara/mycat:v1
      envFrom:
        - configMapRef:
            name: tomcat-cm

